version: "3.8"
services:
  minecraft-server:
    build: .
    volumes:
      - type: bind
        source: ./config/eula.txt
        target: /minecraft/data/eula.txt
      - type: bind
        source: ./config/server.properties
        target: /minecraft/data/server.properties
      - data:/minecraft/data
      - jars:/minecraft/jars
    stop_grace_period: 1m # give it time to save
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      - MINECRAFT_VERSION=${MINECRAFT_VERSION}
      - JVM_OPTS=${JVM_OPTS}
volumes:
  data:
  jars:
